spring:
   application:
    name: GATEWAY-SERVICE
   cloud :
    gateway :
      routes :
        - id: Service-1
          uri : http://localhost:8080/employees
          predicates:
            - Path= /employees
        - id : Service-2
          uri : http://localhost:8081/employees/id
          predicates:
            - Path= /employees/{id}   
          
eureka:
  client:
   register-with-eureka: true
   fetch registry : true
   service-url : 
     defaultZone : http://localhost:8761/eureka/
      
  instance : 
   hostname : localhost
  
server:
  port : 8989
